

spring:
  data:
    mongodb:
      host: ${rms.db.url}
      port: ${rms.db.port}
      database: ${rms.db.dbname}
    rest:
      base-path: /api
    jackson:
      date-format: yyyy-mm-dd
      serialization:
        write-dates-as-timestamps: false
  mongodb:
    embedded:
      storage:
        database-dir: C:\Users\branb\IdeaProjects\rms-dashboard\src\main\resources\data\db
        oplog-size: 0

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG