

spring:
  data:
    mongodb:
      host: ${rms.db.url}
      port: ${rms.db.port}
      database: ${rms.db.dbname}
    rest:
      base-path: /api
    jackson:
      date-format: yyyy-mm-dd
      serialization:
        write-dates-as-timestamps: false
  mongodb:
    embedded:
      storage:
        database-dir: ${user.home}\Documents\dev\brandy-school-project\src\main\resources\data\test
        oplog-size: 0

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG